import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { BookOpen, CalendarDays, CheckCircle2, ChevronRight, LogIn, Plus, Terminal, Trash2 } from "lucide-react";

type Activity = { id: number; title: string; subject: string; status: "pending" | "in_progress" | "submitted"; dueDate?: string | null; notes?: string | null };
type Log = { time: string; event: string; detail: string; tone?: "blue" | "green" | "amber" };
const demoActivities: Activity[] = [
  { id: 1, title: "Maquetación semántica HTML5", subject: "Programación Web", status: "in_progress", dueDate: "2026-09-12", notes: "Completar etiquetas header, main, section y footer." },
  { id: 2, title: "Prototipo interactivo", subject: "Diseño de Interfaces", status: "pending", dueDate: "2026-09-15", notes: "Documentar eventos DOM y navegación." },
  { id: 3, title: "Modelo de persistencia", subject: "Ingeniería de Software", status: "submitted", dueDate: "2026-09-05", notes: "Evidencia entregada." },
];
function now() { return new Date().toLocaleTimeString("es-ES", { hour: "2-digit", minute: "2-digit", second: "2-digit" }); }

export default function Home() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const activitiesQuery = trpc.aulaTrack.list.useQuery(undefined, { enabled: isAuthenticated });
  const utils = trpc.useUtils();
  const createMutation = trpc.aulaTrack.create.useMutation({ onSuccess: () => { utils.aulaTrack.list.invalidate(); addLog("POST 201", "Actividad persistida mediante sentencia preparada.", "green"); resetForm(); }, onError: (error) => addLog("POST 400", error.message, "amber") });
  const updateMutation = trpc.aulaTrack.update.useMutation({ onSuccess: () => { utils.aulaTrack.list.invalidate(); addLog("PUT 200", "Estado actualizado y persistido.", "green"); }, onError: (error) => addLog("PUT 400", error.message, "amber") });
  const removeMutation = trpc.aulaTrack.remove.useMutation({ onSuccess: () => { utils.aulaTrack.list.invalidate(); addLog("DELETE 200", "Registro eliminado con filtro por propietario.", "amber"); }, onError: (error) => addLog("DELETE 400", error.message, "amber") });
  const [form, setForm] = useState({ title: "", subject: "", dueDate: "", notes: "" });
  const [logs, setLogs] = useState<Log[]>([
    { time: now(), event: "SERVER READY", detail: "AulaTrack conectado a la capa de persistencia.", tone: "blue" },
    { time: now(), event: "AUTH SESSION", detail: isAuthenticated ? "Sesión activa y rutas protegidas disponibles." : "Modo demo: inicia sesión para guardar cambios.", tone: isAuthenticated ? "green" : "amber" },
  ]);
  const [activeView, setActiveView] = useState("Resumen");
  const activities = (isAuthenticated ? (activitiesQuery.data ?? []) : demoActivities) as Activity[];
  const stats = useMemo(() => ({ total: activities.length, progress: activities.filter((x) => x.status === "in_progress").length, submitted: activities.filter((x) => x.status === "submitted").length }), [activities]);
  function addLog(event: string, detail: string, tone: Log["tone"] = "blue") { setLogs((old) => [{ time: now(), event, detail, tone }, ...old].slice(0, 8)); }
  function resetForm() { setForm({ title: "", subject: "", dueDate: "", notes: "" }); }
  function submitForm(event: React.FormEvent) { event.preventDefault(); addLog("POST", "Formulario recibido: validando title, subject y dueDate.", "blue"); if (!isAuthenticated) { addLog("AUTH 401", "Inicia sesión para persistir actividades.", "amber"); return; } createMutation.mutate({ ...form, status: "pending" }); }
  function changeStatus(activity: Activity) { if (!isAuthenticated) { addLog("AUTH 401", "La actualización requiere una sesión activa.", "amber"); return; } const next = activity.status === "pending" ? "in_progress" : activity.status === "in_progress" ? "submitted" : "pending"; updateMutation.mutate({ id: activity.id, data: { status: next } }); }
  useEffect(() => { addLog("GET 200", "Listado de actividades cargado en el cliente.", "green"); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [isAuthenticated]);

  return <div className="app-shell">
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark"><span /></div><div><div className="eyebrow">AULA / TRACK</div><h1>AulaTrack</h1></div></div><div className="top-actions"><div className="gps-status"><BookOpen size={15} /><span>{user ? `Sesión: ${user.name || user.email || "estudiante"}` : "Modo demostración"}</span></div>{isAuthenticated ? <button className="profile-button" onClick={() => logout()}>Cerrar sesión <span>×</span></button> : <button className="profile-button" onClick={() => startLogin()}><LogIn size={14} /> Iniciar sesión</button>}</div></header>
    <div className="workspace"><nav className="sidebar" aria-label="Navegación principal"><div className="nav-label">NAVEGACIÓN</div>{["Resumen", "Actividades", "Calendario", "Evidencias"].map((item) => <button key={item} onClick={() => { setActiveView(item); addLog("NAV", `Vista activa: ${item}.`, "blue"); }} className={activeView === item ? "nav-item active" : "nav-item"}>{item}<ChevronRight size={15} /></button>)}<div className="sidebar-note"><div className="mini-label">ACTIVIDAD 5</div><p>Persistencia y procesamiento backend</p><span>tRPC + MySQL + Sesiones</span></div></nav>
      <main className="content"><div className="content-heading"><div><div className="eyebrow">PROYECTO FINAL / PANEL ACADÉMICO</div><h2>Tu progreso, persistido.</h2><p>Administra tus actividades y verifica cada operación del servidor.</p></div><div className="date-chip">5 SEP 2026 <span>•</span> HITO 3</div></div>
        <section className="stats-grid"><div className="stat-card"><span>ACTIVIDADES</span><strong>{stats.total}</strong><small>GET /aulaTrack.list</small></div><div className="stat-card amber"><span>EN PROGRESO</span><strong>{stats.progress}</strong><small>estado in_progress</small></div><div className="stat-card green"><span>ENTREGADAS</span><strong>{stats.submitted}</strong><small>estado submitted</small></div></section>
        <section className="form-card"><div className="section-header"><div><div className="section-kicker">FORMULARIO / POST <span className="event-tag">SANITIZADO</span></div><h3>Nueva actividad</h3></div><span className="method-badge">POST · JSON</span></div><form onSubmit={submitForm} className="activity-form"><input required minLength={3} maxLength={160} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Título de la actividad" aria-label="Título" /><input required minLength={2} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} placeholder="Asignatura" aria-label="Asignatura" /><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} aria-label="Fecha de entrega" /><button className="add-button" type="submit" disabled={createMutation.isPending}><Plus size={15} /> {createMutation.isPending ? "Guardando..." : "Guardar actividad"}</button></form><textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Nota opcional (se valida en servidor)" aria-label="Notas" /></section>
        <section className="section-header activity-heading"><div><div className="section-kicker">CRUD / ACTIVIDADES <span className="event-tag">OWNER FILTER</span></div><h3>Mis actividades</h3></div><span className="result-count">{isAuthenticated ? "Base de datos" : "Datos de ejemplo"}</span></section>
        {isAuthenticated && activitiesQuery.isLoading && <div className="empty-state">Consultando actividades en la base de datos...</div>}{isAuthenticated && activitiesQuery.isError && <div className="error-state">No se pudo cargar el listado: {activitiesQuery.error.message}</div>}{!activitiesQuery.isLoading && !activitiesQuery.isError && activities.length === 0 && <div className="empty-state">No tienes actividades persistidas todavía. Usa el formulario para crear la primera.</div>}{!activitiesQuery.isLoading && !activitiesQuery.isError && activities.length > 0 && <div className="activity-list">{activities.map((activity) => <article className="activity-row js-evidence-card" key={activity.id}><div className="activity-icon"><CalendarDays size={18} /></div><div className="activity-info"><h4>{activity.title}</h4><p>{activity.subject} · {activity.dueDate || "sin fecha"}</p></div><button disabled={updateMutation.isPending} className={`status-pill ${activity.status}`} onClick={() => changeStatus(activity)}>{updateMutation.isPending ? "Guardando..." : activity.status === "pending" ? "Pendiente" : activity.status === "in_progress" ? "En progreso" : "Entregada"}</button>{isAuthenticated && <button disabled={removeMutation.isPending} className="delete-button" onClick={() => removeMutation.mutate({ id: activity.id })} aria-label={`Eliminar ${activity.title}`}><Trash2 size={15} /></button>}</article>)}</div>}
        <section className="cart-summary"><div><div className="section-kicker">CAPA DE SEGURIDAD</div><h3>{isAuthenticated ? "Ruta protegida disponible" : "Vista de demostración"}</h3></div><div className="cart-total"><span>{isAuthenticated ? "SESSION: ACTIVE" : "SESSION: GUEST"}</span>{!isAuthenticated && <button onClick={() => startLogin()}>Autenticar</button>}</div></section>
      </main>
      <aside className="evidence-panel"><div className="evidence-heading"><div><div className="eyebrow">SERVER / LIVE</div><h3><Terminal size={17} /> Evidencias</h3></div><span className="live-dot">{isAuthenticated ? "AUTH" : "DEMO"}</span></div><div className="evidence-card"><div className="evidence-card-title"><span>RUTA ACTIVA</span><CheckCircle2 size={16} /></div><div className="state-row"><span>GET</span><strong>/api/trpc/aulaTrack.list</strong></div><div className="state-row"><span>POST</span><strong>/aulaTrack.create</strong></div><div className="state-row"><span>DB</span><strong>MySQL + prepared</strong></div></div><div className="console-title"><span>SERVER.LOG / TRAZAS</span><button onClick={() => setLogs([])}>limpiar</button></div><div className="console">{logs.map((log, index) => <div className={`log-entry ${log.tone || ""}`} key={`${log.time}-${index}`}><div><span className="log-time">{log.time}</span><strong>{log.event}</strong></div><p>{log.detail}</p></div>)}{logs.length === 0 && <div className="console-empty">Sin trazas. Ejecuta una operación.</div>}</div><div className="event-legend"><div className="mini-label">REQUISITOS CUBIERTOS</div><div className="legend-grid"><span>GET</span><span>POST</span><span>CRUD</span><span>PDO/PREP</span><span>SESSION</span><span>XSS SAFE</span></div></div></aside>
    </div><footer className="footer"><span>© 2026 AulaTrack</span><span>Actividad 5 · Programación del lado del servidor</span><span>tRPC / Drizzle / MySQL</span></footer>
  </div>;
}
